# Generated by Django 4.0.5 on 2022-07-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCollage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Std_Name', models.CharField(max_length=100)),
                ('Std_Address', models.CharField(max_length=200)),
                ('Std_Age', models.IntegerField()),
                ('Join_Date', models.DateField(auto_now_add=True)),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCollage.coursemodel')),
            ],
        ),
    ]
